### ISSUE TITLE
Foxy + 20.04 Ubuntu

### ISSUE THREAD

**Issue by dorkamotorka** [ada-ros/ada4ros2#46]
Do you think it will work on Ubuntu 20.04 with ROS2 Foxy distro? 

I noticed in readme there is only support for Ubuntu 18.04. Did anyone tried to build it on 20.04? Is there any problem?

**Comment by mosteo** [comment]
Indeed that's outdated information. Current development is carried out on 20.04 and should work without issue. I'll update the readme.

**Comment by mosteo** [comment]
Fixed and closing.
